### ISSUE TITLE
Cannot build with python 2.6

### ISSUE THREAD

**Issue by Zenitur** [CLIUtils/CLI11#148]
```
[100%] Generating include/CLI11.hpp
Traceback (most recent call last):
  File "/home/newel/.hunter/_Base/0056188/ba9bc6b/9f2bad3/Build/CLI11/Source/scripts/MakeSingleHeader.py", line 10, in <module>
    from subprocess import check_output, CalledProcessError
ImportError: cannot import name check_output
gmake[5]: *** [include/CLI11.hpp] Error 1
gmake[4]: *** [CMakeFiles/generate_cli_single_file.dir/all] Error 2
gmake[3]: *** [all] Error 2
```

**Comment by henryiii** [comment]
Are you trying to build the single include? That requires a non-dead version of Python (2.7 or 3.4+). If you don't plan to use the single include (as I am guessing since you are trying to build the repository), just turn it off (`-DCLI11_SINGLE_FILE=OFF`), in which case Python is not needed. If you do need the single include, either generate it with a more recent Python or grab it from the releases, then use that.

We probably should make sure it doesn't automatically try to build with Python if Python 2.7+ is not found, though.

**Comment by henryiii** [comment]
If for some reason you need Py 2.6 support, I would accept a PR. It should not try to build the single include automatically now if it can’t. (Please check)

**Comment by Zenitur** [comment]
**henryiii**, no, it's not neccessary to support Python 2.6 in your product. I just trying to build some mining software, and CLI11 is one of the dependencies.

Full build log in pastebin: https://pastebin.com/xjiMfyXy

**Comment by henryiii** [comment]
Fixed in CLI 1.6.1, as well. Now Hunter needs to be updated.

**Comment by Zenitur** [comment]
Confirm. Now it builds for me
