### PR TITLE
fix: build on Windows ARM64

### PR DESCRIPTION
**Pull request by peterh**
Regression introduced in commit 3cd730b18b563fdd48cd95dfb0174551aa18c3b3

### CODE REVIEW

**Comment by phlptp** [comment]
What was the error your were seeing?

**Comment by peterh** [comment]
The compile error is:
```
C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um\winnt.h(169): fatal error C1189: #error:  "No Target Architecture"
```

You can reproduce it when building for X86_64 by removing the \_AMD64_ lines just above where I added the \_ARM64_ lines.

**Review by phlptp — APPROVED** [review]

**Comment by phlptp** [comment]
Ok,  would having an ARM build on visual studio in a CI test have caught this error?

**Comment by peterh** [comment]
> Ok, would having an ARM build on visual studio in a CI test have caught this error?

The question I think you were asking: Yes: Having a 64-bit ARM build on Visual Studio in a CI would have caught this error.

The question you actually asked: No: In Windows nomenclature, ARM without qualifications is a 32-bit ARM build, and this configuration was already supported. Only 64-bit ARM was broken. 😁

**Comment by phlptp** [comment]
That explains that then,  I was pretty sure I had built this many times on Visual studio ARM but quite possibly not the ARM64 build.
